USE [AdventureWorks]
GO

/****** Object:  Table [dbo].[M_Musteriler]    Script Date: 10.06.2022 12:17:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_Musteriler](
	[MusteriID] [INT] IDENTITY(1,1) NOT NULL,
	[MusteriAd] [NVARCHAR](MAX) NULL,
	[MusteriSoyad] [NVARCHAR](MAX) NULL,
	[MusteriSehir] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_dbo.M_Musteriler] PRIMARY KEY CLUSTERED 
(
	[MusteriID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


